package client

import (
	wbanalytics "github.com/benice2me11/wb-api-client/internal/generated/analytics"
	wbdbs "github.com/benice2me11/wb-api-client/internal/generated/dbs"
	wbdbw "github.com/benice2me11/wb-api-client/internal/generated/dbw"
	wbfbs "github.com/benice2me11/wb-api-client/internal/generated/fbs"
	wbgeneral "github.com/benice2me11/wb-api-client/internal/generated/general"
	wbordersfbw "github.com/benice2me11/wb-api-client/internal/generated/ordersfbw"
	wbproducts "github.com/benice2me11/wb-api-client/internal/generated/products"
	wbreports "github.com/benice2me11/wb-api-client/internal/generated/reports"
)

// Generated API clients (for internal facade wiring).
type GeneralAPIClient = wbgeneral.APIClient
type ProductsAPIClient = wbproducts.APIClient
type FBSAPIClient = wbfbs.APIClient
type DBWAPIClient = wbdbw.APIClient
type DBSAPIClient = wbdbs.APIClient
type ReportsAPIClient = wbreports.APIClient
type AnalyticsAPIClient = wbanalytics.APIClient
type OrdersFBWAPIClient = wbordersfbw.APIClient

// General responses.
type PingGet200Response = wbgeneral.PingGet200Response
type ApiV1SellerInfoGet200Response = wbgeneral.ApiV1SellerInfoGet200Response

// Product cards requests/responses.
type ContentV2CardsUploadPostRequestInner = wbproducts.ContentV2CardsUploadPostRequestInner
type ContentV2CardsUploadAddPostRequest = wbproducts.ContentV2CardsUploadAddPostRequest
type ContentV2CardsUpdatePostRequestInner = wbproducts.ContentV2CardsUpdatePostRequestInner
type ContentV2GetCardsListPostRequest = wbproducts.ContentV2GetCardsListPostRequest
type ContentV2GetCardsListPostRequestSettings = wbproducts.ContentV2GetCardsListPostRequestSettings
type ContentV2GetCardsListPostRequestSettingsCursor = wbproducts.ContentV2GetCardsListPostRequestSettingsCursor
type ContentV2GetCardsListPostRequestSettingsFilter = wbproducts.ContentV2GetCardsListPostRequestSettingsFilter
type ContentV2GetCardsListPost200Response = wbproducts.ContentV2GetCardsListPost200Response
type ContentV2GetCardsListPost200ResponseCardsInner = wbproducts.ContentV2GetCardsListPost200ResponseCardsInner
type ContentV2GetCardsListPost200ResponseCardsInnerCharacteristicsInner = wbproducts.ContentV2GetCardsListPost200ResponseCardsInnerCharacteristicsInner
type ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner = wbproducts.ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner
type ContentV2GetCardsListPost200ResponseCardsInnerSizesInner = wbproducts.ContentV2GetCardsListPost200ResponseCardsInnerSizesInner
type ContentV2GetCardsListPost200ResponseCardsInnerTagsInner = wbproducts.ContentV2GetCardsListPost200ResponseCardsInnerTagsInner
type ContentV2CardsLimitsGet200Response = wbproducts.ContentV2CardsLimitsGet200Response
type ContentV2CardsLimitsGet200ResponseData = wbproducts.ContentV2CardsLimitsGet200ResponseData
type ContentV2CardsDeleteTrashPostRequest = wbproducts.ContentV2CardsDeleteTrashPostRequest
type ContentV2CardsDeleteTrashPost200Response = wbproducts.ContentV2CardsDeleteTrashPost200Response
type ContentV2CardsRecoverPost200Response = wbproducts.ContentV2CardsRecoverPost200Response
type RequestPublicViewerPublicErrorsTableListV2 = wbproducts.RequestPublicViewerPublicErrorsTableListV2
type ResponsePublicViewerPublicErrorsTableListV2 = wbproducts.ResponsePublicViewerPublicErrorsTableListV2
type ModelsErrorTableListPublicRespV2 = wbproducts.ModelsErrorTableListPublicRespV2
type ModelsErrorTableListPublicRespV2Item = wbproducts.ModelsErrorTableListPublicRespV2Item
type SwaggerPublicErrorsCursorInput = wbproducts.SwaggerPublicErrorsCursorInput
type SwaggerPublicErrorsOrderV2 = wbproducts.SwaggerPublicErrorsOrderV2
type ViewerContractPublicErrorsCursorOutput = wbproducts.ViewerContractPublicErrorsCursorOutput
type ResponseCardCreate = wbproducts.ResponseCardCreate

// Prices/discounts requests/responses.
type ApiV2UploadTaskPostRequest = wbproducts.ApiV2UploadTaskPostRequest
type ApiV2UploadTaskSizePostRequest = wbproducts.ApiV2UploadTaskSizePostRequest
type ApiV2HistoryGoodsTaskGet200Response = wbproducts.ApiV2HistoryGoodsTaskGet200Response
type ApiV2ListGoodsFilterGet200Response = wbproducts.ApiV2ListGoodsFilterGet200Response
type ApiV2ListGoodsFilterPostRequest = wbproducts.ApiV2ListGoodsFilterPostRequest
type ApiV2ListGoodsSizeNmGet200Response = wbproducts.ApiV2ListGoodsSizeNmGet200Response
type GoodsList = wbproducts.GoodsList
type TaskCreated = wbproducts.TaskCreated

// Warehouses/inventory requests/responses.
type ApiV3StocksWarehouseIdPostRequest = wbproducts.ApiV3StocksWarehouseIdPostRequest
type ApiV3StocksWarehouseIdPost200Response = wbproducts.ApiV3StocksWarehouseIdPost200Response
type ApiV3StocksWarehouseIdPost200ResponseStocksInner = wbproducts.ApiV3StocksWarehouseIdPost200ResponseStocksInner
type ApiV3StocksWarehouseIdPutRequest = wbproducts.ApiV3StocksWarehouseIdPutRequest
type ApiV3StocksWarehouseIdPutRequestStocksInner = wbproducts.ApiV3StocksWarehouseIdPutRequestStocksInner
type ApiV3StocksWarehouseIdPut406Response = wbproducts.ApiV3StocksWarehouseIdPut406Response
type ApiV3StocksWarehouseIdDeleteRequest = wbproducts.ApiV3StocksWarehouseIdDeleteRequest
type StocksWarehouseErrorInner = wbproducts.StocksWarehouseErrorInner
type StocksWarehouseErrorInnerDataInner = wbproducts.StocksWarehouseErrorInnerDataInner
type Office = wbproducts.Office
type Warehouse = wbproducts.Warehouse
type ApiV3WarehousesPostRequest = wbproducts.ApiV3WarehousesPostRequest
type ApiV3WarehousesPost201Response = wbproducts.ApiV3WarehousesPost201Response
type ApiV3WarehousesWarehouseIdPutRequest = wbproducts.ApiV3WarehousesWarehouseIdPutRequest
type StoreContactRequestBody = wbproducts.StoreContactRequestBody
type StoreContactRequestBodyContactsInner = wbproducts.StoreContactRequestBodyContactsInner
type ApiV3DbwWarehousesWarehouseIdContactsGet200Response = wbproducts.ApiV3DbwWarehousesWarehouseIdContactsGet200Response
type ApiV3DbwWarehousesWarehouseIdContactsGet200ResponseContactsInner = wbproducts.ApiV3DbwWarehousesWarehouseIdContactsGet200ResponseContactsInner

// Media files requests/responses.
type ContentV3MediaSavePostRequest = wbproducts.ContentV3MediaSavePostRequest
type ContentV3MediaFilePost200Response = wbproducts.ContentV3MediaFilePost200Response

// FBS requests/responses.
type ApiV3OrdersGet200Response = wbfbs.ApiV3OrdersGet200Response
type ApiV3OrdersNewGet200Response = wbfbs.ApiV3OrdersNewGet200Response
type ApiV3OrdersStatusPostRequest = wbfbs.ApiV3OrdersStatusPostRequest
type ApiV3OrdersStatusPost200Response = wbfbs.ApiV3OrdersStatusPost200Response
type ApiV3OrdersStatusHistoryPostRequest = wbfbs.ApiV3OrdersStatusHistoryPostRequest
type ApiV3OrdersStatusHistoryPost200Response = wbfbs.ApiV3OrdersStatusHistoryPost200Response

// DBW requests/responses.
type ApiV3DbwOrdersGet200Response = wbdbw.ApiV3DbwOrdersGet200Response
type ApiV3DbwOrdersNewGet200Response = wbdbw.ApiV3DbwOrdersNewGet200Response
type ApiV3DbwOrdersStatusPostRequest = wbdbw.ApiV3DbwOrdersStatusPostRequest
type ApiV3DbwOrdersStatusPost200Response = wbdbw.ApiV3DbwOrdersStatusPost200Response

// DBS requests/responses.
type ApiV3DbsOrdersGet200Response = wbdbs.ApiV3DbsOrdersGet200Response
type ApiV3DbsOrdersNewGet200Response = wbdbs.ApiV3DbsOrdersNewGet200Response
type ApiOrdersRequestV2 = wbdbs.ApiOrdersRequestV2
type ApiOrderStatusesV2 = wbdbs.ApiOrderStatusesV2
type DBSCode = wbdbs.Code

// NewDBSCode builds DBS confirmation/rejection code value from a plain string.
func NewDBSCode(value string) DBSCode {
	code := wbdbs.NewCode()
	code.SetCode(value)
	return *code
}

// Reports requests/responses.
type CreateTaskResponse = wbreports.CreateTaskResponse
type CreateTaskResponseData = wbreports.CreateTaskResponseData
type GetTasksResponse = wbreports.GetTasksResponse
type GetTasksResponseData = wbreports.GetTasksResponseData
type ExciseReportRequest = wbreports.ExciseReportRequest
type ExciseReportResponse = wbreports.ExciseReportResponse
type StocksItem = wbreports.StocksItem
type OrdersItem = wbreports.OrdersItem
type SalesItem = wbreports.SalesItem
type ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInner = wbreports.ApiV1WarehouseRemainsTasksTaskIdDownloadGet200ResponseInner
type ApiV1AcceptanceReportTasksTaskIdDownloadGet200ResponseInner = wbreports.ApiV1AcceptanceReportTasksTaskIdDownloadGet200ResponseInner
type ResponsePaidStorageInner = wbreports.ResponsePaidStorageInner
type ApiV1AnalyticsAntifraudDetailsGet200Response = wbreports.ApiV1AnalyticsAntifraudDetailsGet200Response
type ApiV1AnalyticsAntifraudDetailsGet200ResponseDetailsInner = wbreports.ApiV1AnalyticsAntifraudDetailsGet200ResponseDetailsInner
type ApiV1AnalyticsBannedProductsBlockedGet200Response = wbreports.ApiV1AnalyticsBannedProductsBlockedGet200Response
type ApiV1AnalyticsBannedProductsBlockedGet200ResponseReportInner = wbreports.ApiV1AnalyticsBannedProductsBlockedGet200ResponseReportInner
type ApiV1AnalyticsBannedProductsShadowedGet200Response = wbreports.ApiV1AnalyticsBannedProductsShadowedGet200Response
type ApiV1AnalyticsBannedProductsShadowedGet200ResponseReportInner = wbreports.ApiV1AnalyticsBannedProductsShadowedGet200ResponseReportInner
type ApiV1AnalyticsBrandShareBrandsGet200Response = wbreports.ApiV1AnalyticsBrandShareBrandsGet200Response
type ApiV1AnalyticsBrandShareGet200Response = wbreports.ApiV1AnalyticsBrandShareGet200Response
type ApiV1AnalyticsBrandShareGet200ResponseReportInner = wbreports.ApiV1AnalyticsBrandShareGet200ResponseReportInner
type ApiV1AnalyticsBrandShareParentSubjectsGet200Response = wbreports.ApiV1AnalyticsBrandShareParentSubjectsGet200Response
type ApiV1AnalyticsBrandShareParentSubjectsGet200ResponseDataInner = wbreports.ApiV1AnalyticsBrandShareParentSubjectsGet200ResponseDataInner
type ApiV1AnalyticsGoodsLabelingGet200Response = wbreports.ApiV1AnalyticsGoodsLabelingGet200Response
type ApiV1AnalyticsGoodsLabelingGet200ResponseReportInner = wbreports.ApiV1AnalyticsGoodsLabelingGet200ResponseReportInner
type ApiV1AnalyticsGoodsReturnGet200Response = wbreports.ApiV1AnalyticsGoodsReturnGet200Response
type ApiV1AnalyticsGoodsReturnGet200ResponseReportInner = wbreports.ApiV1AnalyticsGoodsReturnGet200ResponseReportInner
type ApiV1AnalyticsRegionSaleGet200Response = wbreports.ApiV1AnalyticsRegionSaleGet200Response
type ApiV1AnalyticsRegionSaleGet200ResponseReportInner = wbreports.ApiV1AnalyticsRegionSaleGet200ResponseReportInner
type GetDeductions200Response = wbreports.GetDeductions200Response
type GetDeductions200ResponseData = wbreports.GetDeductions200ResponseData
type GetDeductions200ResponseDataReportsInner = wbreports.GetDeductions200ResponseDataReportsInner
type MeasurementPenalties = wbreports.MeasurementPenalties
type MeasurementPenaltiesData = wbreports.MeasurementPenaltiesData
type MeasurementPenaltiesDataReportsInner = wbreports.MeasurementPenaltiesDataReportsInner
type WHM = wbreports.WHM
type WHMData = wbreports.WHMData
type WHMDataReportsInner = wbreports.WHMDataReportsInner

// Analytics requests/responses.
type ProductsRequest = wbanalytics.ProductsRequest
type ProductsRequestPastPeriod = wbanalytics.ProductsRequestPastPeriod
type ProductsRequestSelectedPeriod = wbanalytics.ProductsRequestSelectedPeriod
type ProductHistoryRequest = wbanalytics.ProductHistoryRequest
type GroupedHistoryRequest = wbanalytics.GroupedHistoryRequest
type MainRequest = wbanalytics.MainRequest
type TableGroupRequest = wbanalytics.TableGroupRequest
type TableDetailsRequest = wbanalytics.TableDetailsRequest
type ProductSearchTextsRequest = wbanalytics.ProductSearchTextsRequest
type ProductOrdersRequest = wbanalytics.ProductOrdersRequest
type InventoryRequest = wbanalytics.InventoryRequest
type TableGroupRequestSt = wbanalytics.TableGroupRequestSt
type TableProductRequest = wbanalytics.TableProductRequest
type CommonSizeFilters = wbanalytics.CommonSizeFilters
type CommonShippingOfficeFilters = wbanalytics.CommonShippingOfficeFilters
type ItemRatingRequest = wbanalytics.ItemRatingRequest
type ItemRatingResponse = wbanalytics.ItemRatingResponse
type ApiV2NmReportDownloadsPostRequest = wbanalytics.ApiV2NmReportDownloadsPostRequest
type InventoryHistoryReportReq = wbanalytics.InventoryHistoryReportReq
type InventoryHistoryReportReqParams = wbanalytics.InventoryHistoryReportReqParams
type InventoryMetricsReportReq = wbanalytics.InventoryMetricsReportReq
type SalesFunnelGroupReq = wbanalytics.SalesFunnelGroupReq
type SalesFunnelGroupReqParams = wbanalytics.SalesFunnelGroupReqParams
type SalesFunnelProductReq = wbanalytics.SalesFunnelProductReq
type SalesFunnelProductReqParams = wbanalytics.SalesFunnelProductReqParams
type SearchReportGroupReq = wbanalytics.SearchReportGroupReq
type SearchReportGroupReqParams = wbanalytics.SearchReportGroupReqParams
type SearchReportProductReq = wbanalytics.SearchReportProductReq
type SearchReportProductReqParams = wbanalytics.SearchReportProductReqParams
type SearchReportTextReq = wbanalytics.SearchReportTextReq
type SearchReportTextReqParams = wbanalytics.SearchReportTextReqParams
type NmReportGetReportsResponse = wbanalytics.NmReportGetReportsResponse
type NmReportGetReportsResponseDataInner = wbanalytics.NmReportGetReportsResponseDataInner
type NmReportCreateReportResponse = wbanalytics.NmReportCreateReportResponse
type NmReportRetryReportRequest = wbanalytics.NmReportRetryReportRequest
type NmReportRetryReportResponse = wbanalytics.NmReportRetryReportResponse
type PostSalesFunnelProducts200Response = wbanalytics.PostSalesFunnelProducts200Response
type PostSalesFunnelProducts200ResponseData = wbanalytics.PostSalesFunnelProducts200ResponseData
type ProductHistoryResponseInner = wbanalytics.ProductHistoryResponseInner
type PostSalesFunnelGroupedHistory200Response = wbanalytics.PostSalesFunnelGroupedHistory200Response
type ApiV2SearchReportReportPost200Response = wbanalytics.ApiV2SearchReportReportPost200Response
type ApiV2SearchReportTableGroupsPost200Response = wbanalytics.ApiV2SearchReportTableGroupsPost200Response
type ApiV2SearchReportTableDetailsPost200Response = wbanalytics.ApiV2SearchReportTableDetailsPost200Response
type ApiV2SearchReportProductSearchTextsPost200Response = wbanalytics.ApiV2SearchReportProductSearchTextsPost200Response
type ApiV2SearchReportProductOrdersPost200Response = wbanalytics.ApiV2SearchReportProductOrdersPost200Response
type PostV1StocksReportWbWarehouses200Response = wbanalytics.PostV1StocksReportWbWarehouses200Response
type ApiV2StocksReportProductsGroupsPost200Response = wbanalytics.ApiV2StocksReportProductsGroupsPost200Response
type ApiV2StocksReportProductsProductsPost200Response = wbanalytics.ApiV2StocksReportProductsProductsPost200Response
type ApiV2StocksReportProductsSizesPost200Response = wbanalytics.ApiV2StocksReportProductsSizesPost200Response
type ApiV2StocksReportOfficesPost200Response = wbanalytics.ApiV2StocksReportOfficesPost200Response
type PostV1ItemRating200Response = wbanalytics.PostV1ItemRating200Response
type Period = wbanalytics.Period
type PeriodInv = wbanalytics.PeriodInv
type PeriodItemRating = wbanalytics.PeriodItemRating
type PeriodOrdersRequest = wbanalytics.PeriodOrdersRequest
type StockType = wbanalytics.StockType
type OrderBy = wbanalytics.OrderBy
type OrderByGrTe = wbanalytics.OrderByGrTe
type OrderByItemRating = wbanalytics.OrderByItemRating
type OrderByMainAndDetails = wbanalytics.OrderByMainAndDetails
type OrderByMode = wbanalytics.OrderByMode
type TextLimit = wbanalytics.TextLimit
type CommonInfo = wbanalytics.CommonInfo
type CommonInfoAdvertisedProducts = wbanalytics.CommonInfoAdvertisedProducts
type CommonInfoSupplierRating = wbanalytics.CommonInfoSupplierRating
type CommonProductFilters = wbanalytics.CommonProductFilters
type CommonReportFilters = wbanalytics.CommonReportFilters
type CommonResponseProperties = wbanalytics.CommonResponseProperties
type TableGroupResponse = wbanalytics.TableGroupResponse
type TableGroupResponseSt = wbanalytics.TableGroupResponseSt
type TableGroupField = wbanalytics.TableGroupField
type TableDetailsResponse = wbanalytics.TableDetailsResponse
type TableProductResponse = wbanalytics.TableProductResponse
type TableShippingOfficeResponse = wbanalytics.TableShippingOfficeResponse
type TableSizeResponse = wbanalytics.TableSizeResponse

// Orders FBW requests/responses.
type ModelsGood = wbordersfbw.ModelsGood
type ModelsGoodInSupply = wbordersfbw.ModelsGoodInSupply
type ModelsGoodInBox = wbordersfbw.ModelsGoodInBox
type ModelsBox = wbordersfbw.ModelsBox
type ModelsOptionsResultModel = wbordersfbw.ModelsOptionsResultModel
type ModelsOptionsResultModelResultInner = wbordersfbw.ModelsOptionsResultModelResultInner
type ModelsOptionsResultModelResultInnerError = wbordersfbw.ModelsOptionsResultModelResultInnerError
type ModelsOptionsResultModelResultInnerWarehousesInner = wbordersfbw.ModelsOptionsResultModelResultInnerWarehousesInner
type ModelsWarehousesResultItems = wbordersfbw.ModelsWarehousesResultItems
type ModelsTransitTariff = wbordersfbw.ModelsTransitTariff
type ModelsVolumeTariff = wbordersfbw.ModelsVolumeTariff
type ModelsSuppliesFiltersRequest = wbordersfbw.ModelsSuppliesFiltersRequest
type ModelsDateFilterRequest = wbordersfbw.ModelsDateFilterRequest
type ModelsHandySupplyStatus = wbordersfbw.ModelsHandySupplyStatus
type ModelsSupply = wbordersfbw.ModelsSupply
type ModelsSupplyDetails = wbordersfbw.ModelsSupplyDetails
type ModelsErrorModel = wbordersfbw.ModelsErrorModel
type ApiV1AcceptanceOptionsPost401Response = wbordersfbw.ApiV1AcceptanceOptionsPost401Response
type ApiV1AcceptanceOptionsPost402Response = wbordersfbw.ApiV1AcceptanceOptionsPost402Response

// CSV oneOf helpers mirror generated constructors from the internal analytics client.
func InventoryHistoryReportReqAsApiV2NmReportDownloadsPostRequest(v *InventoryHistoryReportReq) ApiV2NmReportDownloadsPostRequest {
	return wbanalytics.InventoryHistoryReportReqAsApiV2NmReportDownloadsPostRequest(v)
}

func InventoryMetricsReportReqAsApiV2NmReportDownloadsPostRequest(v *InventoryMetricsReportReq) ApiV2NmReportDownloadsPostRequest {
	return wbanalytics.InventoryMetricsReportReqAsApiV2NmReportDownloadsPostRequest(v)
}

func SalesFunnelGroupReqAsApiV2NmReportDownloadsPostRequest(v *SalesFunnelGroupReq) ApiV2NmReportDownloadsPostRequest {
	return wbanalytics.SalesFunnelGroupReqAsApiV2NmReportDownloadsPostRequest(v)
}

func SalesFunnelProductReqAsApiV2NmReportDownloadsPostRequest(v *SalesFunnelProductReq) ApiV2NmReportDownloadsPostRequest {
	return wbanalytics.SalesFunnelProductReqAsApiV2NmReportDownloadsPostRequest(v)
}

func SearchReportGroupReqAsApiV2NmReportDownloadsPostRequest(v *SearchReportGroupReq) ApiV2NmReportDownloadsPostRequest {
	return wbanalytics.SearchReportGroupReqAsApiV2NmReportDownloadsPostRequest(v)
}

func SearchReportProductReqAsApiV2NmReportDownloadsPostRequest(v *SearchReportProductReq) ApiV2NmReportDownloadsPostRequest {
	return wbanalytics.SearchReportProductReqAsApiV2NmReportDownloadsPostRequest(v)
}

func SearchReportTextReqAsApiV2NmReportDownloadsPostRequest(v *SearchReportTextReq) ApiV2NmReportDownloadsPostRequest {
	return wbanalytics.SearchReportTextReqAsApiV2NmReportDownloadsPostRequest(v)
}

func Int32AsTextLimit(v *int32) TextLimit {
	return wbanalytics.Int32AsTextLimit(v)
}
